### ISSUE TITLE
URL spaces and Query Parameters Missing from link by Driver

### ISSUE THREAD

**Issue by JariHanah** [FlowingCode/ShareEasy#10]
Hello, found an issue, each driver seems to have issues with Query parameters.

Test Link has two query parameters:
param1=Value Space
lang=en

Link to test
`https://google.com/hello/?param1=Value%20Space&lang=en
`
Twitter & Telegram & WhatsApp Driver Missing %20 for spaces, and only includes the First query: 
`https://google.com/hello/?param1=Value Space 
`
Facebook Driver shows only the first parameter:
`https://google.com/hello/?param1=Value%20Space
`

I think the issue happens if the parameter has spaces.

**Comment by paodb** [comment]
I've been testing this and most of the drivers links are missing URI encoding for the `shareLink` attribute. It's a simple update on the connector file.

**Comment by JariHanah** [comment]
Thanks, will it be with the same Maven version?

**Comment by paodb** [comment]
Hello @JariHanah. The fix will be available in the next release of the component, it should be version 2.0.0. We will let you know when the release is ready.

**Comment by paodb** [comment]
Fix was released in version 2.0.0.
