### ISSUE TITLE
Customize Copy URL?

### ISSUE THREAD

**Issue by JariHanah** [FlowingCode/ShareEasy#8]
I can define a message and a URL for twitter/facebook/whatsapp etc buttons, however, can I do the same with copy url? Specifically, I wish I can have the user copy a specific URL not the website that is hosting the page..

Thank you,

**Comment by paodb** [comment]
Share Easy component is a wrapper of Sharee javscript library. The limitation comes from it: https://github.com/parsagholipour/sharee/blob/2b7bcfa65e3b3742d83b3e3065a583f0f5550ed2/src/lib/drivers/CopyDriver.ts#L28C5-L28C41. Will investigate if we could make the copy driver to also take in consideration the shareLink option on our component.
